--POPULATE TABLE FOR MTY RETURN
DROP TABLE EQPRO_NAG_IB_BKG_PRED;
CREATE TABLE EQPRO_NAG_IB_BKG_PRED AS
SELECT IB.SNAPSHOT_ID             
      ,IB.SHIPMENT_NUMBER         
      ,IB.MVMT_SPEC_REF_NUM       
      ,IB.CNTR_TEU                
      ,IB.CNTR_SIZE               
      ,IB.CNTR_TYPE               
      ,IB.CGO_GRP                 
      ,IB.CGO_NATURE              
      ,IB.LADEN_PICKUP_FCIL_CDE   
      ,IB.LADEN_PICKUP_OPZONE_CDE 
      ,IB.IB_LAST_HUB_FCIL_CDE    
      ,IB.MTY_RTN_FCIL_CDE        
      ,IB.MTY_RTN_OPZONE_CDE      
      ,IB.CNEE_CDE                
      ,IB.CNEE_NME                
      ,IB.L_POD_CDE               
      ,IB.L_POD_FCIL_CDE          
      ,IB.L_POD_OPZONE_CDE        
      ,IB.L_POD_TERR_CDE          
      ,IB.L_SVC_LOOP_ABBRV        
      ,IB.L_VSL_CDE               
      ,IB.L_VOY_NUM               
      ,IB.L_VOY_DIR               
      ,IB.ETA_AT_POD              
      ,IB.ETA_AT_IB_LAST_HUB      
      ,IB.ETA_AT_MTY_RTN          
      ,IB.ETA_AT_MTY_RTN AS ETA_AT_MTY_RTN_PRED
      ,SFT.VGM_WT AS MTY_RTN_TRANSITTIME_PRED
      ,IB.ETA_AT_MTY_RTN AS ETA_AT_MTY_RTN_ACTUAL
      ,(SELECT TO_DATE(SUBSTR(MIN(START_DT_GMT_IODT),1,14),'YYYYMMDDHH24MISS') 
      FROM SFT_CMS_ROUTE_LEG WHERE IB.MVMT_SPEC_REF_NUM=MVMT_SPEC_REF_NUM 
        AND ROUTE_LEG_TYPE='InboundDoor') MTY_RTN_START_DT
      ,(SELECT TO_DATE(SUBSTR(MAX(COMPL_DT_GMT_IODT),1,14),'YYYYMMDDHH24MISS') 
      FROM SFT_CMS_ROUTE_LEG WHERE IB.MVMT_SPEC_REF_NUM=MVMT_SPEC_REF_NUM 
        AND ROUTE_LEG_TYPE='InboundDoor') MTY_RTN_COMPL_DT
      ,(SELECT ROUND(24*(TO_DATE(SUBSTR(MAX(COMPL_DT_GMT_IODT),1,14),'YYYYMMDDHH24MISS')
      - TO_DATE(SUBSTR(MIN(START_DT_GMT_IODT),1,14),'YYYYMMDDHH24MISS')),4) 
        FROM SFT_CMS_ROUTE_LEG WHERE IB.MVMT_SPEC_REF_NUM=MVMT_SPEC_REF_NUM 
        AND ROUTE_LEG_TYPE='InboundDoor') AS MTY_RTN_TRANSITTIME_ACTUAL
      ,SFT.CNTR_NUM
      ,CASE WHEN SFT.CGO_NATURE='GC' THEN 1 ELSE 0 END AS GC_IND
      ,SFT.PCT_IND
      ,SFT.RF_IND
      ,SFT.DG_IND
      ,SFT.AW_IND
      ,SFT.SOC_IND
      ,CASE WHEN SFT.SHIPMENT_BOUND='N' THEN 1 ELSE 0 END AS IS_NORTH_BOUND
      ,CASE WHEN SFT.SHIPMENT_BOUND='E' THEN 1 ELSE 0 END AS IS_EAST_BOUND
      ,CASE WHEN SFT.SHIPMENT_BOUND='S' THEN 1 ELSE 0 END AS IS_SOUTH_BOUND
      ,CASE WHEN SFT.SHIPMENT_BOUND='W' THEN 1 ELSE 0 END AS IS_WEST_BOUND
      ,CASE WHEN SFT.IB_HAULAGE='Merchant' THEN 0
      WHEN SFT.IB_HAULAGE='Carrier' THEN 1 END AS IS_CARRIER_IND
      ,SFT.TARIFF_CODE
      ,SFT.VGM_WT
      ,SFT.BL_CCP_CDE
      ,IB.REC_CRE_DT              
      ,IB.REC_UPD_DT  
      ,0 AS BOX_COUNT
      ,SFT.CGO_BRIEF_DESC            
FROM EQPRO_NAG_IB_BKG IB, IR4_IN.SFT_CMS_BASIC_INFO SFT
WHERE IB.SNAPSHOT_ID=1739
AND IB.MVMT_SPEC_REF_NUM = SFT.MVMT_SPEC_REF_NUM;

--PUT NULL FOR PREDICTED COLUMNS; TO BE UPDATED LATER
UPDATE EQPRO_NAG_IB_BKG_PRED
SET ETA_AT_MTY_RTN_PRED=NULL
    ,ETA_AT_MTY_RTN_ACTUAL=NULL
    ,MTY_RTN_TRANSITTIME_PRED=NULL 
WHERE SNAPSHOT_ID=1739;

--UPDATE BOX COUNT PER SHIPMENT
UPDATE EQPRO_NAG_IB_BKG_PRED IB
  SET  BOX_COUNT = (SELECT COUNT(1) FROM SFT_CMS_BASIC_INFO WHERE SHIPMENT_NUMBER= IB.SHIPMENT_NUMBER)
WHERE  EXISTS(SELECT 1 FROM SFT_CMS_BASIC_INFO WHERE MVMT_SPEC_REF_NUM=IB.MVMT_SPEC_REF_NUM)
  AND  SNAPSHOT_ID=1739;

--FIND TOP CONSIGNEE PER FCIL PAIR AND MAX TRANSIT TIME
DROP TABLE EQPRO_NAG_IB_BKG_CUST_PRED;
CREATE TABLE EQPRO_NAG_IB_BKG_CUST_PRED AS
SELECT E.BL_CCP_CDE,
ROUND(AVG(E.MTY_RTN_TRANSITTIME_ACTUAL)/24,1) AS AVG_TT_DAYS,
ROUND(STDDEV(E.MTY_RTN_TRANSITTIME_ACTUAL)/24,1) AS STD_TT_DAYS ,
ROUND(AVG(E.MTY_RTN_TRANSITTIME_ACTUAL/24)-(1.29*STDDEV(E.MTY_RTN_TRANSITTIME_ACTUAL/24)),1) AS MIN_AVG_TT_DAYS,
ROUND(AVG(E.MTY_RTN_TRANSITTIME_ACTUAL/24)+(1.29*STDDEV(E.MTY_RTN_TRANSITTIME_ACTUAL/24)),1) AS MAX_AVG_TT_DAYS,
ROUND(MIN(E.MTY_RTN_TRANSITTIME_ACTUAL)/24,1) AS MIN_TT_DAYS,
ROUND(MAX(E.MTY_RTN_TRANSITTIME_ACTUAL)/24,1) AS MAX_TT_DAYS,
COUNT(1) AS CNT
FROM EQPRO_NAG_IB_BKG_PRED E 
WHERE E.SNAPSHOT_ID=1739
AND  E.LADEN_PICKUP_FCIL_CDE='LGB10'
AND E.MTY_RTN_FCIL_CDE='LGB10'
AND E.MTY_RTN_TRANSITTIME_ACTUAL > 0
AND 0 =(CASE WHEN (E.CNTR_SIZE='20' AND E.VGM_WT > 17000) THEN 1 
                 WHEN (E.CNTR_SIZE!='20' AND E.VGM_WT > 20000) THEN 1 ELSE 0 END)
HAVING COUNT(1) >= 100
GROUP BY  E.BL_CCP_CDE  
ORDER BY CNT DESC;

--EXTRACT TOP COMMODITY PER BL CUSTOMER
DROP TABLE EQPRO_NAG_IB_BKG_TOP_CGO_PRED;
CREATE TABLE EQPRO_NAG_IB_BKG_TOP_CGO_PRED AS
SELECT * FROM (
      SELECT E.BL_CCP_CDE,
      UPPER(SFT.CGO_BRIEF_DESC) CGO_BRIEF_DESC,
      RANK() OVER (PARTITION BY E.BL_CCP_CDE ORDER BY E.BL_CCP_CDE,COUNT(1) DESC ) AS RN,
      COUNT(1) AS CNT
      FROM EQPRO_NAG_IB_BKG_PRED E, SFT_CMS_BASIC_INFO SFT
      WHERE E.SNAPSHOT_ID=1739
      AND SFT.MVMT_SPEC_REF_NUM=E.MVMT_SPEC_REF_NUM
      AND  E.LADEN_PICKUP_FCIL_CDE='LGB10'
      AND E.MTY_RTN_FCIL_CDE='LGB10'
      AND E.MTY_RTN_TRANSITTIME_ACTUAL > 0
      GROUP BY  E.BL_CCP_CDE,UPPER(SFT.CGO_BRIEF_DESC
              ) 
) WHERE RN=1;

--UPDATE MAIN TABLE WITH TOP COMMODITY
UPDATE EQPRO_NAG_IB_BKG_PRED  P
SET TOP_CGO_DESC = (
  SELECT CGO_BRIEF_DESC 
  FROM EQPRO_NAG_IB_BKG_TOP_CGO_PRED 
  WHERE BL_CCP_CDE = P.BL_CCP_CDE
   AND ROWNUM =1
   );

SELECT E.CNTR_NUM        
      ,DECODE(E.CNTR_SIZE,'40',1,0) IS_40
      ,DECODE(E.CNTR_SIZE,'45',1,0) IS_45
      ,DECODE(E.CNTR_TYPE,'GP',1,0) IS_GP
      ,DECODE(E.CNTR_TYPE,'HQ',1,0) IS_HQ
       ,ROUND(E.VGM_WT/1000) VGM_WT
      ,CASE WHEN (E.CNTR_SIZE='20' AND E.VGM_WT > 17000) THEN 1 
            WHEN (E.CNTR_SIZE!='20' AND E.VGM_WT > 20000) THEN 1 ELSE 0 END IS_OVERWT   
      ,(CASE WHEN INSTR(UPPER(SFT.CGO_BRIEF_DESC),(SELECT CGO_BRIEF_DESC FROM EQPRO_NAG_IB_BKG_TOP_CGO_PRED WHERE BL_CCP_CDE=E.BL_CCP_CDE AND ROWNUM=1)) > 0  
      THEN  1 ELSE 0 END) IS_TOP_COMMODITY
      ,BOX_COUNT
      ,TO_CHAR(ETA_AT_POD,'D') AS ETA_DD
      ,TO_CHAR(ETA_AT_POD,'MM') AS ETA_MO
      ,ROUND( MTY_RTN_TRANSITTIME_ACTUAL ) MTY_RTN_TRANSITTIME_HRS              
FROM EQPRO_NAG_IB_BKG_PRED E,SFT_CMS_BASIC_INFO SFT
WHERE E.SNAPSHOT_ID=1739 
AND SFT.MVMT_SPEC_REF_NUM=E.MVMT_SPEC_REF_NUM